[package]
name = "keg_tracker"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A command-line application for tracking beer kegs and their contents"

[dependencies]
